project:
  math:
    \AFunc: \mathrm{A}
    \ALvl: \boldsymbol{\mathit{A}}
    \ANrm: A
    \APFac: \text{\pmb{\Thorn}}
    \APFacDefn: \hyperlink{APFacDefn}{\textrm{APF}}
    \APRte: \text{\thorn}
    \ARKurl: \href{https://econ-ark.org}{Econ-ARK}
    \Alive: \mathcal{L}
    \Alt: \grave
    \BFunc: \mathrm{B}
    \BLvl: \boldsymbol{\mathit{B}}
    \BNrm: B
    \CARA: \alpha
    \CDF: \mathcal{F}
    \CEndFunc: '{\mathfrak{C}}'
    \CFunc: \mathrm{C}
    \CLvl: \boldsymbol{\mathit{C}}
    \CNrm: C
    \CRRA: \rho
    \Chi: '{\mathrm{X}}'
    \DFunc: \mathrm{D}
    \DLvl: \boldsymbol{\mathit{D}}
    \DNrm: D
    \DeprFac: \daleth
    \DiePrb: \mathsf{D}
    \DiscAlt: ''
    \DiscAltuAdj: \Min{\Min{\beth}}
    \DiscFac: \beta
    \DiscFacAlt: \beth
    \DiscFacLiv: \Min{\DiscFacRaw}
    \DiscFacRaw: \beta
    \DiscRte: \nu
    \EEndMap: '{\mathsf{E}}'
    \EFunc: \mathrm{E}
    \ELvl: \boldsymbol{\mathit{E}}
    \ENrm: E
    \EPermShkInv: \Ex[\permShk^{-1}]
    \EPrem: \pmb{\varphi}
    \EpremLog: \varphi
    \Ex: '{\mathbb{E}}'
    \FDist: '{\mathcal{F}}'
    \FFunc: \mathrm{F}
    \FLvl: \boldsymbol{\mathit{F}}
    \FNrm: F
    \GFunc: \mathrm{G}
    \GLvl: \boldsymbol{\mathit{G}}
    \GPFac: \APFac/{\PermGroFac}
    \GPFacMod: \APFac/{\PermGroFacAdj}
    \GPFacRaw: \APFac/{\PermGroFac}
    \GPRte: \text{\thorn}_{\PermGroRte}
    \HARKdocs: \href{https://docs.econ-ark.org}{documentation}
    \HARKrepo: \texttt{\href{https://github.com/econ-ark/HARK}{HARK}}
    \HFunc: \mathrm{H}
    \HLvl: \boldsymbol{\mathit{H}}
    \HNrm: H
    \IFunc: \mathrm{I}
    \ILvl: \boldsymbol{\mathit{I}}
    \INrm: I
    \IncUnemp: \mu
    \InvEPermShkInv: \Min{\permShk}
    \JFunc: \mathrm{J}
    \JLvl: \boldsymbol{\mathit{J}}
    \JNrm: J
    \KFunc: \mathrm{K}
    \KLvl: \boldsymbol{\mathit{K}}
    \KNrm: K
    \Kap: K
    \LFunc: \mathrm{L}
    \LLvl: \boldsymbol{\mathit{L}}
    \Labor: \mathrm{L}
    \LivPrb: \Alive
    \Lvl: \boldsymbol
    \MFunc: \mathrm{M}
    \MLvl: \boldsymbol{\mathit{M}}
    \MNrm: M
    \MPC: \kappa
    \MPCFunc: \pmb{\kappa}
    \MPCmax: \Max{\MPC}
    \MPCmaxmax: \Max{\Max{\MPC}}
    \MPCmaxmin: \Max{\Min{\MPC}}
    \MPCmin: \Min{\MPC}
    \MPCminmin: \Min{\Min{\MPC}}
    \MPSmax: \RPFac
    \MPSmin: \pZero^{1/\CRRA} \RPFac
    \Max: \overline
    \Mean: '{\mathbb{M}}'
    \Min: \underline
    \NFunc: \mathrm{N}
    \NLvl: \boldsymbol{\mathit{N}}
    \NNrm: N
    \Nrml: ''
    \OFunc: \mathrm{O}
    \OLvl: \boldsymbol{\mathit{O}}
    \Opt: ''
    \PDV: '{\mathbb{P}}'
    \PFunc: \mathrm{P}
    \PLvl: \boldsymbol{\mathit{P}}
    \PNrm: P
    \PermGroFac: \mathcal{G}
    \PermGroFacAdj: \Min{\PermGroFac}
    \PermGroFacAgg: \mathscr{G}
    \PermGroFacRnd: \Rnd{\PermGroFac}
    \PermGroFacuAdj: \Min{\Min{\PermGroFac}}
    \PermGroRte: g
    \PermLvl: \PermLvlAgg
    \PermLvlAgg: \boldsymbol{\mathit{P}}
    \PermLvlAll: \mathfrak{P}
    \PermShk: \PermShkAgg
    \PermShkAgg: \Psi
    \PermShkAll: \mathbf{\Psi}
    \PermShkAllStd: \std_{\PermShkAll}
    \PermShkAllVar: \std^{2}_{\PermShkAll}
    \PopGroFac: ''
    \PopnGroFac: \Xi
    \PopnGroRte: \xi
    \PopnLvl: \pmb{\mathrm{N}}
    \PtyGroFac: ''
    \PtyGroRte: ''
    \QFunc: \mathrm{Q}
    \QLvl: \boldsymbol{\mathit{Q}}
    \RBoro: \bar{\Rfree}
    \REMARK: \href{https://github.com/econ-ark/REMARK}{REMARK}
    \RFunc: \mathrm{R}
    \RLvl: \boldsymbol{\mathit{R}}
    \RNrm: \cancel{\mathbf{R}}
    \RNrmByG: \mathscr{R}
    \RNrmByGRnd: \Rnd{\mathscr{R}}
    \RPFac: \APFac/{\Rfree}
    \RPRte: \text{\thorn}_{\rfree}
    \RSave: \Min{\Rfree}
    \Reals: ''
    \Rfree: \mathsf{R}
    \RfreeEff: \bar{\Rfree}
    \Risky: \mathbf{R}
    \Rnd: \tilde
    \Rnorm: '{\mathcal{R}}'
    \Rport: \mathfrak{R}
    \SFunc: \mathrm{S}
    \SLvl: \boldsymbol{\mathit{S}}
    \SNrm: S
    \TFunc: \mathrm{T}
    \TLvl: \boldsymbol{\mathit{T}}
    \TMap: ''
    \TargetNrm: \hat
    \TaxAmt: T
    \TaxRte: \tau
    \TranShkAgg: \Theta
    \TranShkAggStd: \std_{\TranShkAgg}
    \TranShkAggVar: \std^{2}_{\TranShkAgg}
    \TranShkAll: \pmb{\Xi}
    \TranShkEmp: \Theta
    \UFunc: \mathrm{U}
    \ULvl: \boldsymbol{\mathit{U}}
    \VFunc: \mathrm{V}
    \VLvl: \boldsymbol{\mathit{V}}
    \VNrm: V
    \WFunc: \mathrm{W}
    \WGroFac: \ensuremath{\mathrm{G}}
    \WGroRte: \mathrm{g}
    \WLvl: \boldsymbol{\mathit{W}}
    \Wage: '{\mathsf{W}}'
    \XFunc: \mathrm{X}
    \XLvl: \boldsymbol{\mathit{X}}
    \YFunc: \mathrm{Y}
    \YLvl: \boldsymbol{\mathit{Y}}
    \YNrm: Y
    \ZFunc: \mathrm{Z}
    \ZLvl: \boldsymbol{\mathit{Z}}
    \ZNrm: Z
    \aFunc: \mathrm{a}
    \aLvl: \boldsymbol{\mathit{a}}
    \aMin: '{\Min{\aNrm}}'
    \aNrm: a
    \avg: \bar
    \bFunc: \mathrm{b}
    \bLvl: \boldsymbol{\mathit{b}}
    \bNrm: b
    \cEndFunc: '{\mathfrak{c}}'
    \cFunc: \mathrm{c}
    \cFuncAbove: ''
    \cFuncBelow: ''
    \cFuncLvl: ''
    \cLvl: \boldsymbol{\mathit{c}}
    \cNrm: c
    \chiFunc: \pmb{\chi}
    \cncl: ''
    \cov: ''
    \dFunc: \mathrm{d}
    \dLvl: \boldsymbol{\mathit{d}}
    \dNrm: d
    \deprRte: \delta
    \diePrb: \mathsf{d}
    \discRte: \nu
    \eFunc: \mathrm{e}
    \eLvl: \boldsymbol{\mathit{e}}
    \eNrm: e
    \eprem: \phi
    \erate: '{\cancel{\mho}}'
    \fDist: '{\mathcal{f}}'
    \fFunc: \mathrm{f}
    \fLvl: \boldsymbol{\mathit{f}}
    \fNrm: f
    \gFunc: \mathrm{g}
    \gLvl: \boldsymbol{\mathit{g}}
    \hFunc: \mathrm{h}
    \hLvl: \boldsymbol{\mathit{h}}
    \hNrm: h
    \iFunc: \mathrm{i}
    \iLvl: \boldsymbol{\mathit{i}}
    \iNrm: i
    \jFunc: \mathrm{j}
    \jLvl: \boldsymbol{\mathit{j}}
    \jNrm: j
    \kFunc: \mathrm{k}
    \kLvl: \boldsymbol{\mathit{k}}
    \kNrm: k
    \kap: k
    \lNrm: l
    \labor: \ell
    \leiShare: \zeta
    \livPrb: \ell
    \lst: \texttt{last}
    \mFunc: \mathrm{m}
    \mLvl: \boldsymbol{\mathit{m}}
    \mNrm: m
    \mTrgNrm: \TargetNrm{\mNrm}
    \muFuncInv: '{\rotatebox{180}{$\uFunc$}}'
    \nFunc: \mathrm{n}
    \nLvl: \boldsymbol{\mathit{n}}
    \nxt: \texttt{next}
    \oLvl: \boldsymbol{\mathit{o}}
    \oNrm: o
    \pFunc: \mathrm{p}
    \pLvl: \boldsymbol{\mathit{p}}
    \pNotZero: (1-\pZero)
    \pNrm: p
    \pZero: \wp
    \permGroFacInd: \mathit{G}
    \permLvl: \permLvlInd
    \permLvlInd: \boldsymbol{\mathit{p}}
    \permShk: \permShkInd
    \permShkInd: \psi
    \permShkIndMax: \Max{\permShkInd}
    \permShkIndMin: \Min{\permShkInd}
    \popGroRte: ''
    \prstShk: \phi
    \prstShkAgg: \Phi
    \prstShkInd: \phi
    \prstShkIndMax: \Max{\prstShkInd}
    \prstShkIndMin: \Min{\prstShkInd}
    \ptyGroFac: ''
    \ptyGroRte: ''
    \qLvl: \boldsymbol{\mathit{q}}
    \qNrm: q
    \rFunc: \mathrm{r}
    \rLvl: \boldsymbol{\mathit{r}}
    \rboro: \bar{\rfree}
    \rfree: \mathsf{r}
    \risky: \mathbf{r}
    \riskyELev: \boldsymbol{r}
    \riskyELog: \risky
    \riskyshare: '{\varsigma}'
    \riskyvar: \std^{2}_{\risky}
    \rnorm: '{\mathit{r}}'
    \rport: \mathfrak{r}
    \rsave: \Min{\rfree}
    \sFunc: \mathrm{s}
    \sLvl: \boldsymbol{\mathit{s}}
    \sNrm: s
    \std: \sigma
    \tLvl: \boldsymbol{\mathit{t}}
    \tax: \tau
    \taxFree: \cancel{\tax}
    \tranShkAll: \pmb{\xi}
    \tranShkAllStd: \std_{\tranShkAll}
    \tranShkAllVar: \std^{2}_{\tranShkAll}
    \tranShkEmp: \theta
    \tranShkEmpMax: \Max{\tranShkEmp}
    \tranShkEmpMin: \Min{\tranShkEmp}
    \tranShkInd: \xi
    \tranShkIndStd: \std_{\tranShkInd}
    \tranShkIndVar: \std^{2}_{\tranShkInd}
    \tranShkMax: \Max{\xi}
    \tranShkMin: \Min{\xi}
    \uFunc: \mathrm{u}
    \uFuncInv: \rotatebox{180}{$\uFunc$}
    \uInvEuPermShk: \Min{\Min{\permShk}}
    \uLvl: \boldsymbol{\mathit{u}}
    \uP: \mathrm{u}^{\prime}
    \uPP: \mathrm{u}^{\prime\prime}
    \unins: '{\zeta}'
    \urate: '{\mho}'
    \util: u
    \vFunc: \mathrm{v}
    \vFuncLvl: \mathbf{v}
    \vLvl: \boldsymbol{\mathit{v}}
    \vNrm: v
    \wFunc: \mathrm{w}
    \wLvl: \boldsymbol{\mathit{w}}
    \wage: '{\mathsf{w}}'
    \weight: \omega
    \xFunc: \mathrm{x}
    \xLvl: \boldsymbol{\mathit{x}}
    \yFunc: \mathrm{y}
    \yLvl: \boldsymbol{\mathit{y}}
    \yNrm: y
    \zFunc: \mathrm{z}
    \zLvl: \boldsymbol{\mathit{z}}
    \zNrm: z
